version: '3.8'

services:
  carbackend:
    image: 231324680416.dkr.ecr.ap-south-1.amazonaws.com/carbackend:latest
    container_name: carbackend
    ports:
      - "8001:8000"
    restart: always
    networks:
      - carprice-net

  carfrontend:
    image: 231324680416.dkr.ecr.ap-south-1.amazonaws.com/carfrontend:latest
    container_name: carfrontend
    ports:
      - "80:3000"
    depends_on:
      - carbackend
    restart: always
    networks:
      - carprice-net

networks:
  carprice-net:
    driver: bridge
