services:
  backend:
    build: ./backend
    image: carbackend:latest
    container_name: carbackend
    ports:
      - "8001:8000"
    environment:
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID:-}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET:-}
      RAZORPAY_WEBHOOK_SECRET: ${RAZORPAY_WEBHOOK_SECRET:-}
      RAZORPAY_ACCOUNT_ID: ${RAZORPAY_ACCOUNT_ID:-acc_RMCL2XxhTCiDHJ}
      RAZORPAY_MERCHANT_ID: ${RAZORPAY_MERCHANT_ID:-RMCL2XxhTCiDHJ}
      RAZORPAY_PLAN_STARTER_ID: ${RAZORPAY_PLAN_STARTER_ID:-plan_ThYwyJ8SEhnLT2}
      RAZORPAY_PLAN_STANDARD_ID: ${RAZORPAY_PLAN_STANDARD_ID:-plan_ThYz7eyDEvheTI}
      RAZORPAY_PLAN_PRO_ID: ${RAZORPAY_PLAN_PRO_ID:-plan_ThYzrhgOX3xmzu}
      RAZORPAY_MERCHANT_NAME: ${RAZORPAY_MERCHANT_NAME:-Dateai}
      # AWS Credentials
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-AKIATLXAGQDQKWYORLFR}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-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}
      AWS_REGION: ${AWS_REGION:-ap-south-1}
      AWS_SES_SENDER_EMAIL: ${AWS_SES_SENDER_EMAIL:-pg42876914@gmail.com}
      # S3
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:-finalcar-user-uploads-2026}
      # DynamoDB Tables
      DYNAMODB_TABLE_USERS: ${DYNAMODB_TABLE_USERS:-repairlens-users}
      DYNAMODB_TABLE_PREDICTIONS: ${DYNAMODB_TABLE_PREDICTIONS:-repairlens-predictions}
      DYNAMODB_TABLE_PAYMENTS: ${DYNAMODB_TABLE_PAYMENTS:-repairlens-payments}
      DYNAMODB_TABLE_OTP: ${DYNAMODB_TABLE_OTP:-repairlens-otp}
      DYNAMODB_TABLE_WEBHOOKS: ${DYNAMODB_TABLE_WEBHOOKS:-repairlens-webhooks}
      DYNAMODB_TABLE_COUPONS: ${DYNAMODB_TABLE_COUPONS:-repairlens-coupon-redemptions}

    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    image: carfrontend:latest
    container_name: carfrontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always
