version: '3.8'

services:
  backend:
    build: ./backend
    image: carbackend:latest
    container_name: carbackend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    image: carfrontend:latest
    container_name: carfrontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always